const node = (category, title, desc, owner, engine, sla, status, statusColor, inputs, outputs, criteria, notes) => ({
  category, title, desc, owner, engine, sla, status, statusColor, inputs, outputs, criteria, notes,
});

export const pipelineData = {
  'agent-01': node('AUTONOMOUS SPECIFICATION AGENT', 'AGENT-01 : REQUIREMENT INTAKE & SCOPE ARBITER',
    'Autonomous parsing and formalization of stakeholder requirements.', 'Autonomous Agent // E. Giemsa (Product Scope)', 'Claude 3.5 Sonnet / LLM Arbiter', '14.2s intake cycle', 'ACTIVE & VALIDATED', 'text-gate-emerald',
    'Jira tickets, PRD markdown documents, historical battery fleet telemetry.', 'Structured Gherkin scenario matrices, deterministic scope specifications.',
    ['Unambiguous user story decomposition with zero conflicting criteria.', 'Automated mapping of high-voltage battery test requirements to ISO 26262 clauses.', 'Pre-computation of test execution feasibility and simulation cost.'],
    'Provides clean, mathematically sound inputs into downstream interface architecture.'),
  'hitl-01': node('HUMAN-IN-THE-LOOP CHECKPOINT', 'HITL-01 : PRODUCT OWNER SCOPE SIGN-OFF',
    'Strategic verification of synthesized scope and business commitments.', 'Eric Giemsa (Software Solution Owner)', 'Human Decision Authority', '&lt; 4 hr turnaround', 'SIGNED OFF // APPROVED', 'text-hitl-blue',
    'Synthesized scope package, estimated cloud compute spend, customer timeline.', 'Cryptographically signed scope manifest approving code synthesis.',
    ['Alignment with quarterly commercial battery-test roadmaps.', 'Budget verification for hardware-in-the-loop laboratory compute hours.', 'Formal acceptance of Gherkin functional bounds.'],
    'Guarantees that autonomous coding agents only develop profitable and verified features.'),
  'agent-02': node('SYSTEMS & CONTRACT AGENT', 'AGENT-02 : SYSTEMS & INTERFACE ARCHITECT',
    'Deterministic generation of API contracts, data models, and bus protocols.', 'Autonomous Agent // Systems Engineering', 'OpenAPI 3.1 Synthesis / Z3 SMT Solver', '6.4s contract sweep', 'CONTRACT BOUND', 'text-gate-emerald',
    'Approved Gherkin criteria from HITL-01, existing schema definitions.', 'OpenAPI 3.1 schemas, Protobuf v3 definitions, CAN/EtherCAT payload layouts.',
    ['Zero schema drift across distributed microservices.', 'Sub-microsecond deserialization efficiency for high-rate battery cycler telemetry.', 'Backward compatibility verification against existing Keysight SaaS clients.'],
    'Re-evaluates system interfaces whenever Loop L-03 detects schema discrepancies.'),
  'agent-03': node('AUTONOMOUS SYNTHESIS AGENT', 'AGENT-03 : AUTONOMOUS CODE SYNTHESIS',
    'High-velocity code generation across services, drivers, and unit test suites.', 'Autonomous Agent // Core Engineering', 'Specialized Code Synthesis Model', '22.8s full suite build', 'ACTIVE // READY', 'text-gate-emerald',
    'OpenAPI contracts, data schemas, unit test requirements.', 'Clean TypeScript/Rust microservices, FPGA real-time driver bindings, unit tests.',
    ['100% test-driven development (TDD) coverage on core business logic.', 'Adherence to strict functional safety and memory determinism constraints.', 'Clean AST structures ready for static analysis inspection.'],
    'Receives AST remediation patches from Loop L-01 and bug diagnostics from Loop L-02.'),
  'agent-04': node('STATIC ANALYSIS & SECURITY AGENT', 'AGENT-04 : STATIC ANALYSIS & SECURITY REVIEWER',
    'Formal code verification, abstract syntax tree (AST) inspection, and CVE audits.', 'Autonomous Agent // Security Operations', 'AST Analysis Engine / Semgrep / Snyk', '8.1s scan execution', 'AST PASSING (100%)', 'text-gate-emerald',
    'Synthesized source code and compiled binaries from Agent-03.', 'AST remediation diffs, security audit logs, compliance certificates.',
    ['Zero high or critical CVE vulnerabilities in dependencies.', 'Deterministic memory safety without unbounded heap allocation.', 'Immediate routing of linter or type errors into Loop L-01 for auto-healing.'],
    'Operates the inner healing loop (L-01) with a strict budget of 3 retries.'),
  'agent-05': node('DYNAMIC INTEGRATION & HIL HARNESS', 'AGENT-05 : DYNAMIC QA & HIL TESTBED HARNESS',
    'Automated end-to-end regression across simulated physics and physical testbeds.', 'Autonomous Agent // QA Engineering', 'Keysight Test Automation / HIL Runner', '145s full suite run', 'HOLDING // JITTER DETECTED', 'text-technical-orange',
    'Containerized microservices, high-voltage battery cycler HIL interface.', 'End-to-end pass/fail telemetry, cycle jitter logs, bug tickets.',
    ['Strict &lt; 2.0ms real-time loop determinism on 1000V/1200A cycler interfaces.', 'Zero thermal runaway limit breaches during stress cycling.', 'Automatic generation of regression reproduction scripts.'],
    'Detected 2.84ms loop delay, which triggered the HITL-02 escalation checkpoint.'),
  'hitl-02': node('CRITICAL EXCEPTION CHECKPOINT', 'HITL-02 : CRITICAL EXCEPTION ARBITER',
    'Human escalation gate triggered when autonomous retries exceed budgeted limits.', 'Eric Giemsa (Technical Project Lead)', 'Engineering Management Authority', '&lt; 2 hr SLA', 'HOLDING (ESCALATED)', 'text-technical-orange',
    'Loop L-02 diagnostic report, real-time HIL timing traces, jitter histograms.', 'Approved architectural workaround, FPGA latency shim, or driver patch.',
    ['Root-cause disambiguation between hardware bus contention and software queuing.', 'Authorization of driver-level bypass or refactoring of real-time priorities.', 'Safety verification that voltage protection interlocks remain completely unaffected.'],
    'The central alert callout on the canvas is pinned to this critical intervention gate.'),
  'agent-06': node('DOCUMENTATION & PACKAGING AGENT', 'AGENT-06 : AUTONOMOUS LIVING DOCS & PACKAGING',
    'Generation of interactive API documentation, changelogs, and OCI containers.', 'Autonomous Agent // DevOps', 'DocFX / Container Builder', '18.4s package build', 'PREPARED FOR GATE', 'text-gate-emerald',
    'Verified code repository, passing test manifests, git history.', 'Versioned OpenAPI portals, signed OCI container images, release notes.',
    ['Automatic synchronization between code implementation and public API docs.', 'Cryptographic signing of container artifacts using Cosign/Sigstore.', 'Zero undocumented breaking changes across public endpoints.'],
    'Prepares the release candidate bundle for the final canary deployment gate.'),
  'hitl-03': node('PRODUCTION CANARY GATE', 'HITL-03 : PRODUCTION CANARY ARBITER',
    'Final human verification checkpoint before customer SaaS fleet deployment.', 'Eric Giemsa (Software Solution Owner)', 'Release Governance Authority', 'Scheduled Release Window', 'AWAITING GATE CLEARANCE', 'text-hitl-blue',
    '1% canary metric telemetry, latency distributions, error budget burn rate.', 'Authorized production rollout token for 100% cloud customer base.',
    ['Zero error budget regression during 1% canary observation window.', 'Confirmation that battery-test customers experience zero reporting interruptions.', 'Formal sign-off for global customer release.'],
    'Ensures zero downtime and continuous SLA fulfillment for enterprise clients.'),
  'loop-01': node('CLOSED AUTONOMOUS FEEDBACK LOOP', 'LOOP L-01 : INNER DEV AST HEALING LOOP',
    'Closed-loop cycle between Static Analysis (Agent-04) and Code Synthesis (Agent-03).', 'Autonomous Feedback Machine', 'AST Differ & LLM Micro-Patch', '&lt; 4.0s per repair try', 'NOMINAL (MAX 3 TRIES)', 'text-gate-amber',
    'Syntax errors, type mismatch logs, memory safety linter warnings.', 'Targeted code diffs applied to source files.',
    ['Solves 89% of compiler and typing faults without human involvement.', 'Hard cap of 3 attempts prevents infinite loop hallucinations.'],
    'Eliminates developer busywork on basic syntax, types, and linter formatting.'),
  'loop-02': node('CLOSED AUTONOMOUS FEEDBACK LOOP', 'LOOP L-02 : VERIFICATION BUG-BOUNTY LOOP',
    'Automated defect diagnosis and patch generation from QA integration failures.', 'Autonomous Feedback Machine', 'Regression Tracer & Patch Agent', '&lt; 45s per cycle', 'ESCALATED AT 3/3 TRIES', 'text-technical-orange',
    'HIL hardware failure logs, assertion stack traces, timing jitter graphs.', 'Context-enriched defect reports and speculative code patches.',
    ['Isolates failing test cases to specific commit lines.', 'Escalates to HITL-02 if 3 consecutive patch attempts fail.'],
    'Triggered the current escalation because real-time jitter persisted across 3 tries.'),
  'loop-03': node('SYSTEMS FEEDBACK LOOP', 'LOOP L-03 : ARCHITECTURE CONTRACT DRIFT LOOP',
    'Re-alignment loop between Integration QA (Agent-05) and Interface Architect (Agent-02).', 'Systems Governance', 'OpenAPI Spec Reconciler', 'On-demand sync', 'MONITORING', 'text-hitl-blue',
    'Undocumented payload changes, timing contract violations.', 'Updated interface specifications and schema migration patches.',
    ['Prevents silent payload drift from breaking downstream services.', 'Enforces contract-first engineering discipline across all agents.'],
    'Maintains architectural integrity across large multi-team projects.'),
  deploy: node('RUNTIME ENVIRONMENT', 'PRODUCTION : GLOBAL BATTERY SAAS RUNTIME',
    'Multi-tenant cloud platform processing global battery laboratory telemetry.', 'SRE & Operations Team', 'Kubernetes / Distributed Cloud', '99.98% High Availability', 'OPERATIONAL', 'text-gate-emerald',
    'Approved release packages from HITL-03.', 'Real-time battery degradation analytics, executive KPI dashboards.',
    ['Zero interruption to active high-voltage cycling tests worldwide.', 'Sub-second query responses for historical battery cell datasets.'],
    'Where deep engineering reliability translates directly into enterprise customer value.'),
};
